In [1]:
import numpy as np

# 创建数组
数学上将一维数组称为向量，将二维数组称为矩阵，将三维及以上的数组称为"张量tensor"或"多维数组"。

In [5]:
b = np.array([[1, 2], [3, 4]])
b = np.arange(-10, 10, 2)  # 类似range，返回ndarray
b.reshape(2, 5)  # 变为二维数组
b.flatten()  # 降为一维数组
print(np.ones(3))  # [1. 1. 1.]
print(np.zeros((2, 3)))  # 二维数组 两行三列

[1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]]


## 创建随机数数组
pytorch和tensorflow同理，都是相同的方法
np.random.randn(2,3)
torch.randn(2,3)
tf.random.randn(2,3)

In [26]:
rdm = np.random.RandomState(seed=12)  # 每次运行生成的随机数都是一样的
print(rdm.randint(-10, 10, 15, np.int32).reshape(3, 5))  # 随机整数

[[  1  -4   7  -8  -7]
 [ -7   2   6   7  -5]
 [  3  -8   1   0 -10]]


### 正态分布

In [21]:
# 生成正态分布的随机数，默认均值为0，标准差为1 (维度，mean=均值，stddev=标准差)
print(rdm.randn(2, 3))  # 返回2*2的标准正态分布随机数
print(rdm.normal(0.5, 1, [2, 3]))  # 均值0.5 方差1的正态分布

[[ 0.8093955  -0.14492863  0.00704372]
 [ 0.03111137 -0.53237072 -0.73523089]]
[[ 0.55530143 -0.42862724]
 [ 0.56501984 -1.04038097]]


### 均匀分布

In [27]:
print(rdm.rand(2,3))  # [0,1)见的均匀分布
print(rdm.uniform(0, 1, [2, 3]))

[[0.67599758 0.98364716 0.48153021]
 [0.91253883 0.18987634 0.14797388]]
[[1.90726736 1.68432507 1.95772873]
 [1.45605092 1.56314114 1.80126538]]


## 数组属性 shape dtype

In [10]:
a = np.array([1, 2, 3, 4, 5], dtype=np.int64)
print(a.shape, a.dtype)
a = a.astype(np.float32)  # 类型转换
print(a.dtype)

(5,) int64
float32


## 数组运算 dot
逐元素 加减乘除 + - * /
函数 np.sqrt(x) np.exp(x)

In [2]:
# 数组运算
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

In [3]:
a.shape, a.ndim  # (2, 2) 2维

((2, 2), 2)

In [4]:
a.dot(b), np.dot(a, b)  # 矩阵乘法 Matrix Product

(array([[19, 22],
        [43, 50]]),
 array([[19, 22],
        [43, 50]]))

In [ ]:
a > b  # 生成布尔值数组

In [ ]:
np.maximum(a, b)  # 生成一个最大值数组 fmax忽略NaN

In [ ]:
np.vstack((a, b))  # 两个数组按垂直方向叠加

## 统计方法 sum mean std标准差 var方差

In [41]:
a = np.arange(1, 11).reshape(2, 5)
print(a)
print(a.mean(axis=1), np.mean(a))  # 关于axis详见tensorflow
print(np.max(a), np.argmax(a))  # 最大值 最大值的索引
print(np.cumsum(a), "\n" , np.cumprod(a))  # 所有元素的累积和 累计积

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3. 8.] 5.5
10 9
[ 1  3  6 10 15 21 28 36 45 55] 
 [      1       2       6      24     120     720    5040   40320  362880
 3628800]


## 广播
低维c扩展到高维a相同的形状

In [ ]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([10, 20])
print(a + b)

## 数组切片
类似列表切片

In [28]:
a = np.arange(10)
a_slice = a[5:8]
b = a.reshape(2, 5)  # reshape(-1, 1)等价于(n, 1)   -1就是自动根据列数计算行数；
print(b)
print(b[:, 1])  # 提取 列下标=1 的所有元素

[[0 1 2 3 4]
 [5 6 7 8 9]]
[1 6]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


## 布尔型索引|数组 where

In [42]:
a = np.arange(-10, 10).reshape(4, 5)
# 将data中的所有负值都设置为0
# a[a < 0] = 0  # 改变原始值
res = np.where(a > 0, a, 0)  # where(条件, True, False)
print(res)
bools = a > 0
print(a.any(), a.all())  # 是否有一个为True，是否全部为True

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 2 3 4]
 [5 6 7 8 9]]
True False


## 数组转置和轴对换 a.T  transpose

In [17]:
a = np.arange(15).reshape((3, 5))
print(a.T)  # 数组转置
# 高维数组转置见tensorflow笔记 维度变换transpose

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## 排序 交并差集
np.intersect1d(a, b)交集  np.union1d(a, b)并集

In [ ]:
a = np.random.randint(-10, 10, 15, np.int32).reshape(3,5)
b = np.random.randint(-10, 10, 15, np.int32).reshape(3,5)
a.sort(1)  # 对行排序 axis=1
print(a)
print(np.unique(a))  # 返回唯一值并排序  =sorted(set(names))
np.intersect1d(a, b)  # 交集
np.union1d(a, b)  # 并集
np.setdiff1d(a, b)  # 差集=a-交集 在a不在b中的元素

# 使用数组进行数据处理
在一组值(网格型)上计算函数``sqrt(x^2+y^2)``

In [ ]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
z = np.sqrt(xs ** 2 + ys ** 2)
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

## 生成等间隔数值点

In [43]:
x, y = np.mgrid[1:3:1, 2:4:0.5]  # [起始值:结束值:步长，起始值:结束值:步长，... ]  左闭右开
x, y = x.ravel(), y.ravel()  # 将x, y变成一维数组
grid = np.c_[x, y]  # 合并配对为二维张量，生成二维坐标点 (感觉像zip)
print('grid:\n', grid)

grid:
 [[1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [2.  2. ]
 [2.  2.5]
 [2.  3. ]
 [2.  3.5]]
